- backend/ecs_tasks/delete_files/parquet.py
- backend/ecs_tasks/delete_files/requirements.in
- backend/ecs_tasks/delete_files/requirements.txt
- requirements.txt
- templates/template.yaml
By testing the solution with https://github.com/awslabs/game-analytics-pipeline I bumped into an interesting bug.
The ParquetWriter was failing to write a table because between the arrow=>pandas=>arrow conversions, a nullable string was not correctly passed through and set as null instead. That was causing the writer to fail:
```
Unprocessable message: Table schema does not match schema used to create file: 
table:
event_id: string
event_type: string
event_name: string
event_version: string
event_timestamp: int64
client_id: string
user_id: string
session_id: string
application_id: string
application_name: string
event_data: string
metadata: string
custom_event: null vs. 
file:
event_id: string
event_type: string
event_name: string
event_version: string …
```
> Pyarrow schema bugfix

- CHANGELOG.md
- templates/deployment_helper.yaml
- templates/template.yaml
During 0.2 upgrade, I noticed that the copy artifact was correctly performed but the deployment helper didn't wait for the codepipeline to be completed. This should fix (there is already a dependency between custom resources)
> Wait for codepipeline during upgrades

- CHANGELOG.md
- templates/api.yaml
- templates/template.yaml
I mistakenly deployed the solution from local source without properly installing the python dependencies and managed to generate some 5xx on the server. 
Unfortunately, when that happened, the frontend couldn't show any error because the CORS headers weren't being sent for 5xx codes. I think that the SAM usually takes care of that for you but if you override with `GatewayResponses` as we do, you then need to make that a comprehensive list for all the codes that need the CORS headers.
I managed to deploy this change and currently see the code showed in the frontend.
I thought about making it as acceptance, but I think it's probably not needed and I would need to change the code to make it happen, which I think it's not worth.
By submitting this …
> 5xx error handling

- .gitignore
- CHANGELOG.md
- Makefile
- templates/template.yaml
This change intends to improve reliability of the build process. Whilst
having directory targets is semantically nice, it has resulted in a few
occassions where the characteristics of mtimes on directories has
resulted in targets not being built when they should be.
> Convert directory targets to sentinel file targets

- CHANGELOG.md
- backend/ecs_tasks/delete_files/events.py
- tests/unit/ecs_tasks/test_events.py
n/a
Fixes the Forget ECS Task match ID sanitiser to handle integers
> Fix Sanitiser

- CHANGELOG.md
- backend/ecs_tasks/delete_files/parquet.py
- tests/unit/ecs_tasks/test_parquet.py
N/A
Sets preserve index to True when writing Parquet tables. This ensures that datasets which have been written with Pandas indexes can be processed by the solution. Previously an exception would be thrown because the original schema is specified when creating a PyArrow table from the updated pandas dataframe. For more information, see https://arrow.apache.org/docs/python/parquet.html#omitting-the-dataframe-index and https://github.com/apache/arrow/blob/8f3b029122a8f7149e2061c17a74f4add2677a6e/python/pyarrow/pandas_compat.py#L418
> enable handling of parquet data with indexes

- CHANGELOG.md
- templates/state_machine.yaml
- templates/template.yaml
Extends the query queue visibility. This is for an issue I noticed: when processing a dataset with 31 partitions, I was noticing ~50 actual queries. This is because when it was taking more than 2m, the message was going back in the queue, despite the lambda would wait until completion and then correctly put the message in the deletion queue. The impact wasn't impacting functional behaviour (the deletion queue has deduplication) but still, it was impacting time and cost because of duplicated efforts on the Find phase.
With this PR I'm proposing we extend to 30m which is the duration Athena can take to complete a query.
> Extend the query queue visibility timeout

- tests/acceptance/__init__.py
- tests/acceptance/test_job.py
After upgrading pyarrow, a test was failing. I managed to reproduce with an old version and found out there were some changes on type coercion for strings when working directly with Arrow.
I also realised that somehow I didn't run a `make setup` during the last couple of iterations so the failure wasn't being reproduced locally.
Before:
```
for i in table.column(column):
print(type(i))
<class 'pyarrow.lib.StringValue'>
<class 'pyarrow.lib.StringValue'>
<class 'pyarrow.lib.StringValue'>
```
After:
```
<class 'pyarrow.lib.StringScalar'>
<class 'pyarrow.lib.StringScalar'>
<class 'pyarrow.lib.StringScalar'>
```
Use `as_py` to convert to Python string: https://arrow.apache.org/docs/python/generated/pyarrow.StringScalar.html#pyarrow.StringScalar …
> Fix acceptance tests

- CHANGELOG.md
- backend/lambdas/queue/handlers.py
- docs/api/Apis/DeletionQueueApi.md
- docs/api/Models/ListOfCreateDeletionQueueItems.md
- docs/api/Models/ListOfDeletionQueueItem.md
- docs/api/README.md
- frontend/src/utils/gateway.js
- package-lock.json
- package.json
- templates/api.definition.yml
- templates/api.yaml
- tests/acceptance/test_queue.py
- tests/unit/apis/test_queue.py
Adds a batch endpoint to allow populating the queue quicker.
I'm not entirely sure of the API here, we already have a `PATCH /queue` for inserting an item, I thought we could just have a breaking change or keep the API of `queue/matches` compatible with the DELETE one (which uses that). So at least this is not breaking change.
One other thing I'm not sure is if we should set an arbitrary limit given we are subject to API Gateway payload size and response size, for instance 100 items or so?
> Batch handling for deletion queue items

- CHANGELOG.md
- backend/lambdas/tasks/generate_queries.py
- tests/acceptance/conftest.py
- tests/acceptance/test_job.py
- tests/unit/tasks/test_execute_query.py
- tests/unit/tasks/test_generate_queries.py
*Description of changes*
Adds handling for non-string partition types such as int. I opted for keeping the strategy consistent with what we do with matches: we get the partition type from glue, then we cast it during the generate phase, so that the execute inherits the values already casted. 
Credits: I took some code snippets from @ormahler's #188 PR 
> Fix query failures due to incorrect partition casting

- CHANGELOG.md
- backend/lambdas/queue/handlers.py
- tests/acceptance/test_queue.py
I noticed a bug affecting the UI for showing the correct Deletion queue size (for instance Chrome 1(~258 bytes) vs Firefox 1(0 bytes). After some digging, I found firefox is more strict about content-length and needs a header for the frontend to be able to read it (we base the approximate size of the queue to the content-length of the queue api responses).
> Fix Firefox cors issue

- backend/lambdas/data_mappers/handlers.py
- docs/api/Apis/DataMapperApi.md
- docs/api/README.md
- frontend/src/components/pages/NewDataMapper.js
- frontend/src/index.css
- templates/api.definition.yml
- templates/api.yaml
- tests/acceptance/test_data_mappers.py
- tests/unit/data_mappers/test_data_mappers.py
At the moment the PUT data mapper is advertised as Create in API/Frontend and I think this generates confusion. I renamed the "Create" in the backend to be PUT in order to be consistent with API behaviour. I also found and fixed a bug involving doing a PUT for an existing DM that had the same location being prevented from being modified.
In the frontend, I think it makes sense to keep the naming and behaviour as "create", so I decided to add a check to prevent adding a new data mapper with the same ID both on validation phase (by fetching all DMs on page load and then checking synchronously against that) and submit phase (checking one last time to reduce probability of a race condition).
By submitting this pull request, I confirm that my …
> Remove ambiguity between DataMappers Create/Modify/Put

- CHANGELOG.md
- backend/lambdas/tasks/submit_query_results.py
- templates/state_machine.yaml
- templates/template.yaml
- tests/unit/tasks/test_submit_query_results.py
This fixes a FIND_FAILED during querying a dataset that has a large number of results (managed to reproduce with 5000 objects as result in a single partition) triggering an error such as:
```
{
"Error": "States.DataLimitExceeded",
"Cause": "The state/task 'arn:aws:lambda:[redacted]:[redacted]:function:S3F2-StateMachineStack-[redacted]-SubmitQueryResults-[redacted]' returned a result with a size exceeding the maximum number of bytes service limit."
}
```
The reason is that the lambda that stores the results in SQS, then returns the full paths as result, which affects the SF state limit (regardless of excluding it with `ResultPath: null`).
I managed to verify that after this change, the execution succeeds.
As a side note, when I was testing (and the step was …
> Fix SF state limit on submit results

- .gitignore
- CHANGELOG.md
- Makefile
- templates/deployment_helper.yaml
- templates/template.yaml
*Issue #, if available:* #222 
This commit attempts to address #222 by moving the Docker base image
retrieval to the build/release CI stage and including it in the release
artefacts. This version is then loaded in CodeBuild using `docker load`.
Although bundling the docker base image in the packaged artefacts isn't
particularly elegant, it addresses some constraints we have at this
particular time around creating new distribution channels. We may be
able to revisit and improve upon this later.
> Include base image in artefacts

- CHANGELOG.md
- frontend/src/components/BucketPolicyModal.js
- frontend/src/components/CellError.js
- frontend/src/components/pages/DataMappers.js
- frontend/src/utils/glueSerializer.js
- frontend/src/utils/retryWrapper.js
When a Glue Table is deleted, the Data Mappers UI fails to render the list because the Glue API call fails - and the whole UI is unusable. This PR is to show the error and handle deletion/policy generation (which shows an error message from the API).
> Handle Deleted Glue Tables

- CHANGELOG.md
- backend/lambdas/tasks/generate_queries.py
- templates/template.yaml
While working on #198 I discovered that the code for query generation can be improved. We currently create a template of a query object at the beginning of the code snippet, then we duplicate it for any partition combination, and only then, we workout all the queue elements for each partition. Because there is no difference between partitions in terms of queue items logic, we can just workout the queue items earlier and just once, and duplicate for partitioned buckets at the end instead, saving in compute time and making the code a bit simpler.
> Improve query generation code

- CHANGELOG.md
- backend/lambdas/data_mappers/handlers.py
- backend/lambdas/tasks/generate_queries.py
- docs/USER_GUIDE.md
- docs/api/Models/DataMapperQueryExecutorParameters.md
- frontend/package.json
- frontend/src/__tests__/__snapshots__/glueSerializer.js.snap
- frontend/src/components/pages/DataMappers.js
- frontend/src/components/pages/DeletionJob.js
- frontend/src/components/pages/NewDataMapper.js
- frontend/src/utils/gateway.js
- frontend/src/utils/glueSerializer.js
- frontend/src/utils/index.js
- templates/api.definition.yml
- tests/unit/data_mappers/test_data_mappers.py
- tests/unit/tasks/test_generate_queries.py
This is a PR to enable customers to customise the query strategy by declaring the Partition Keys to be used for generating queries.
Let's take an example a large dataset with Partition Keys=[year,month,day] as 3 individual partition keys.
The solution as today will fetch the cartesian product of them and will perform a query for each unique combination of values. 
For example, let's assume daily data starting Feb 1st 2020 and ending March 1st 2021.
With this new feature, a Data Mapper will be able to specify none or any of the Partition Keys:
* With `PartitionKeys=[]` there will be 1 query (no partition keys used)
* With `PartitionKeys=["year"]` there will be 2 queries (y=2020 + y=2021)
* With `PartitionKeys=["month"]` there will be 12 queries
* With …
> Allow to specify granularity for partition querying

- frontend/src/utils/glueSerializer.js
If glue table(s) doesn't contain partition keys, it will fail when creating a new data mapper.
Add a check for partition keys in the glue serializer.
> Fix creating data mapper bug when glue table doesn't have partition keys

- CHANGELOG.md
- backend/ecs_tasks/delete_files/parquet_handler.py
- tests/unit/ecs_tasks/test_parquet.py
Deletion from some parquet files fails on [this line](https://github.com/awslabs/amazon-s3-find-and-forget/blob/master/backend/ecs_tasks/delete_files/parquet_handler.py#L131) with the following error:
> TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
The issue appears to be that `table` gets emptied out on the first iteration, so on the second iteration `indexes` is empty.
Verified that this PR fixes the issue.
> Fix parquet multiple column identifier bug

- CHANGELOG.md
- backend/ecs_tasks/delete_files/requirements.in
- backend/ecs_tasks/delete_files/requirements.txt
- backend/lambda_layers/aws_sdk/requirements.in
- backend/lambda_layers/aws_sdk/requirements.txt
- backend/lambda_layers/boto_utils/python/boto_utils.py
- requirements.txt
- templates/deletion_flow.yaml
- tests/unit/lambda_layers/test_boto_utils.py
This is a PR to fix a bug observed when processing takes more than an hour, causing the expiration of an access token. This is an example of a exception:
```
2021-11-02T07:17:27.424-07:00	[INFO] Generating new file without matches
2021-11-02T08:18:06.356-07:00	[ERROR] ClientError: An error occurred (ExpiredToken) when calling the GetBucketRequestPayment operation: The provided token has expired.
```
I investigated increasing the token validity to 12 hours, but unfortunately the maximum duration for temporary credentials is 1 hour. I decided to setup a mechanism to auto-refresh tokens but then I bumped into this [blogpost](https://ben11kehoe.medium.com/boto3-sessions-and-why-you-should-use-them-9b094eb5ca8e), which also came with a handy python library that I …
> Auto-refresh access tokens used by containers

- CHANGELOG.md
- backend/ecs_tasks/delete_files/main.py
- templates/template.yaml
In #276 I managed to solve the expiration token issue happening when using the s3 boto client by using the library that wraps the session handling. Unfortunately, when doing more testing, I bumped into a new bug: `ObjectUpdateFailed` with `"Unable to retrieve object: Write failed: TypeError(\"'NoneType' object is not subscriptable\")"`.
After doing some digging, I found that while the previous PR solved the issue by refreshing the token from the client (https://github.com/awslabs/amazon-s3-find-and-forget/blob/master/backend/ecs_tasks/delete_files/s3.py#L18-L21), the S3fs client was still using stale credentials. By passing in the session to the s3fs factory, I verified the issue is fixed by artificially creating a 1h sleep and waiting for it to be reproduced and …
> Make sure s3fs uses the session rather than stale token after expiration

- CHANGELOG.md
- backend/ecs_tasks/delete_files/main.py
- backend/ecs_tasks/delete_files/parquet_handler.py
- templates/template.yaml
When processing a job with a large queue, there may be some performance issues in the Forget phase. In particular, with a queue of 10K matches in a dataset of 2 objects of 300MB each, I was able to complete the job only after 50m, as opposite of a couple of minutes when the same dataset had 1 match in the queue (of which the actual compute was a bunch of seconds).
After this improvement, I was able to obtain the same result for the large queue. Note that this helps only with simple matches, as composite still iterate over lists. I plan to address that in a separate PR as I think that is a bit more complex and I need more time to think about it.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> Improve performance for large queues of simple matches

- CHANGELOG.md
- backend/ecs_tasks/delete_files/parquet_handler.py
- templates/template.yaml
Following #279 this is an equivalent improvement for composite matches. I tested again manually a 10K size queue with and without the change in order to prove that the job completed after a couple of seconds with the change, as opposite of being stuck for an hour.
> Improve performance for large queues of composite matches

- CHANGELOG.md
- backend/lambdas/tasks/generate_queries.py
- tests/unit/tasks/test_generate_queries.py
Query generation step times out (i.e. takes longer than 15 minutes) when a table has many partitions. I was able to reproduce the issue in a test environment with a table containing 70000 partitions.
After this change, query generation for the same table completes in about 6 minutes.
> Improve performance of query generation step (#281)

- CHANGELOG.md
- backend/lambdas/tasks/execute_query.py
- tests/unit/tasks/test_execute_query.py
Current find query seems to induce pathological behavior in the query engine for data mappers with multiple column identifiers. We're seeing query runtimes of around 30 minutes for relatively small datasets. As an example, a data mapper with around 7 million rows for a given partition and 15000 match ids in the manifests table is taking around 30 minutes to run.
The cause seems to be the `OR` part of the query in particular. This PR significantly improves performance in this case by using unions instead. With this change, we're seeing query runtimes going from around 30 minutes to under 10 seconds. More details below.
```
SELECT DISTINCT t."$path"
FROM db.table t,
manifests m
WHERE
m."jobid"='xxx' AND
m."datamapperid"='yyy' AND
((cast(t."customer_id" as …
```
> Improve performance of find query for data mappers with multiple column identifiers

- CHANGELOG.md
- templates/state_machine.yaml
2 small changes:
1. `AthenaQueryMaxRetries` parameter was being ignored since it wasn't being picked out in the initial Pass state of the state machine. Added it to the list of parameters.
2. Athena state machine failure was causing job to fail due to transient errors such as the following. Added retry to one of the steps to avoid this issue.
```
{
"error": "Lambda.SdkClientException",
"cause": "Unable to execute HTTP request: Connection reset"
}
```
> Add retries to state machine, Respect AthenaQueryMaxRetries

- CHANGELOG.md
- templates/state_machine.yaml
- templates/template.yaml
The query queue SQS currently has a visibility timeout of 30m, which is the default timeout for Athena queries.
If a customer requests an increase and a query takes more than 30m, a new query will start and possibly result on duplicating results in the deletion SQS queue (we have deduplication there being FIFO, but that is only based on timeframes of approximately 5m). As a result, the Forget phase will have some tasks working on the same object, with the first successfully deleting, and the next failing with an error like: `Unprocessable message: The object s3://<REDACTED> was processed successfully but no rows required deletion`.
I initially thought of solving the issue by making the visibility timeout configurable, but I then thought that there are possibly no …
> Prevent duplicated query executions for long-running queries

- CHANGELOG.md
- backend/ecs_tasks/delete_files/events.py
- backend/ecs_tasks/delete_files/main.py
- backend/lambdas/data_mappers/handlers.py
- backend/lambdas/jobs/handlers.py
- backend/lambdas/jobs/stats_updater.py
- backend/lambdas/tasks/generate_queries.py
- backend/lambdas/tasks/submit_query_results.py
- docs/LIMITS.md
- docs/USER_GUIDE.md
- docs/api/Models/DataMapper.md
- docs/api/Models/Job.md
- docs/api/Models/JobSummary.md
- frontend/src/components/pages/DeletionJob.js
- frontend/src/components/pages/NewDataMapper.js
- frontend/src/utils/gateway.js
- templates/api.definition.yml
- tests/acceptance/conftest.py
- tests/acceptance/test_data_mappers.py
- tests/acceptance/test_job.py
- tests/unit/data_mappers/test_data_mappers.py
- tests/unit/ecs_tasks/conftest.py
- tests/unit/ecs_tasks/test_events.py
- tests/unit/ecs_tasks/test_main.py
- tests/unit/jobs/test_stats_updater.py
- tests/unit/jobs/test_status_updater.py
- tests/unit/tasks/test_generate_queries.py
- tests/unit/tasks/test_submit_query_results.py
Currently a deletion job will fail if objects that were found in the Find phase no longer exist in the Delete phase. This can cause spurious failures when lifecycle policies are configured on a bucket which cause objects to expire.
This PR adds a data mapper parameter to allow users to ignore these errors. The default behavior remains the same.
> Add parameter for ignoring Object Not Found exceptions during deletion

- CHANGELOG.md
- backend/lambdas/tasks/generate_queries.py
- tests/unit/tasks/test_generate_queries.py
When generating the queries, the current logic iterates over the data mappers and casts each match id by calling `cast_to_type`, which itself calls `get_column_info` to fetch info on the column to get the type, which itself always calls `column_mapper` to do stuff that is computationally heavy such as creating a tree that defines the schema, which is important for complex data types (types such as `struct`, `array`, `map`).
With this new change, the columns of each data mapper are converted to a tree calling `column_mapper` only once for each data mapper, so that `get_column_info` can lookup and traverse the tree without repeating the operation for each match id.
The result of this optimisation is important when processing hundreds or thousands of matches. …
> Improve performance for query generation task

- CHANGELOG.md
- backend/lambdas/custom_resources/cleanup_bucket.py
- backend/lambdas/tasks/generate_queries.py
- templates/template.yaml
- tests/unit/crs/test_cr_cleanup_bucket.py
- tests/unit/tasks/test_generate_queries.py
Closes: #319 
Have a default value for the setting, so that upgrading from versions prior to 0.48 succeeds.
Note 1: we are using the same mechanism to fetch variables in 2 other custom resources, but because they are new with 0.48, they are executed on create so this shouldn't happen there.
Note 2: after rebasing doing to the merge of #314 I thought I would update the changelog to make it a bit clearer and I made it part of this PR, as well as some re-formatting due to #314 probably not running the pre-commit format, but it should be nothing big.
> Fix cleanup bucket lambda

- CHANGELOG.md
- backend/ecs_tasks/delete_files/utils.py
- backend/lambdas/tasks/submit_query_results.py
- tests/unit/tasks/test_submit_query_results.py
Improve memory management for the Submit Query Lambda. The current work should be useful when receiving hundreds of thousands of results for a single query. Rather than reading the whole set of results and storing in memory, with this code changes we read in batches using the generator that makes paginated calls to API, and then we save results to SQS earlier and in batches in order to use less memory.
> Submit Query Lambda Performance improvements

- CHANGELOG.md
- backend/ecs_tasks/delete_files/events.py
- backend/ecs_tasks/delete_files/main.py
- backend/ecs_tasks/delete_files/parquet_handler.py
- backend/ecs_tasks/delete_files/s3.py
- templates/template.yaml
- tests/unit/ecs_tasks/test_main.py
This changes follow a troubleshooting for an issue observed with `v0.53` running on Python `3.9.15` where there is a false negative on a Job execution (termination with a partially failed result for an object that was successfully processed).
According to logs, the kill handler (to be executed from the parent process in the ECS task) seems to be intercepted by the children processes during multi-processing. One of the children is working with an old copy of the data, that includes the old message, and fails when cleaning up the message from SQS as it's been deleted already.
```
2022-11-02T10:42:45.602-07:00	[INFO] Fetching messages...
2022-11-02T10:42:45.624-07:00	[INFO] Message received
2022-11-02T10:42:52.291-07:00	[INFO] Downloading and opening …
```
> Force spawn for multiprocessing and consistent PID logging on ECS

- CHANGELOG.md
- backend/lambdas/tasks/generate_queries.py
- tests/unit/tasks/test_generate_queries.py
Closes: #250 
When a match ID is added but it's invalid (for instance, a string in place of an integer that fails to cast to a number), an error is shown not providing data mappers information (needed when having lots of data mappers and adding a match to ALL datamappers). In addition, its value is shown in the logs and it should be masked (with this change, I decided to show the DeletionQueueItemId, which is a auto-generated ID for identifying the item in Dynamo, that you need when you use the Queue API to delete the match).
Note that this could possibly be avoided by adding validation on the Data Mapper level - which currently doesn't do any during Match Id creation. (But that may not be trivial as Match Id API operation is synchronous …
> Better error handling when handling invalid match ids

- CHANGELOG.md
- backend/lambdas/queue/handlers.py
- docs/TROUBLESHOOTING.md
- docs/USER_GUIDE.md
There is a duplicated call to put_item in DDB that has no effect in functionality (put for same ID) but potentially duplicates cost and performance for adding items to the queue. This PR is to remove this redundant call.
It is caused by a mistake when doing the refactoring in https://github.com/awslabs/amazon-s3-find-and-forget/pull/200
> Remove redundant put call to DDB

- CHANGELOG.md
- Makefile
- requirements.in
- requirements.txt
- templates/web_ui.yaml
*Issue #, if available:* N/A
**Update CloudFront to use OAC instead of OAI**
This change updates the Web UI CloudFront distribution to use Origin
Access Control (OAC) for authentication to the S3 origin, instead of the
previous implementation using Origin Access Identity (OAI).
OAC was introduced in August 2022 to supersede OAI. The main benefit of
this change in S3F2 is that OAI is not supported in AWS regions launched
after December 2022, so this change will be necessary to add region
support in the future.
**Bump cfn-lint version**
This is necessary to add support for CloudFront Origin Access Control
parameter/types.
Also adds an ignore rule for cfn-lint rule W3002, which "warn(s) when
properties are configured to only work with the package command".
*PR …
> Update CloudFront to use OAC instead of OAI

- CHANGELOG.md
- Makefile
- backend/lambdas/custom_resources/rerun_pipeline.py
- templates/deployment_helper.yaml
- templates/template.yaml
- tests/unit/crs/test_cr_rerun_pipeline.py
Starting May 25, 2023, CodePipeline doesn't allow anymore polling based S3 sources. New stacks don't poll, and existing stacks with pipelines that haven't ran for more than 30 days, don't start a build when a S3 source is uploaded. As a consequence:
1. New builds of this solution are currently stuck on the "Wait for Container Build" custom resource, as the build never starts
2. Existing deployments of this solution cannot be updated for the same issue.
There is [a (quite convoluted) way to setup Eventbridge to start a deployment, based on CloudTrail and setting up lots of resources](https://docs.aws.amazon.com/codepipeline/latest/userguide/update-change-detection.html#update-change-detection-S3), but we already have a Custom Resource …
> Fix codepipeline build

- CHANGELOG.md
- docs/USER_GUIDE.md
- templates/template.yaml
- templates/web_ui.yaml
N/A
This fixes an issue introduced in
995f9d90bc3049e8a77490bc15fa23d1b785b900 that affected users who have
multiple S3F2 instances deployed within the same AWS account, using the
same ResourcePrefix parameter, but in different regions.
The issue prevented the stack from deploying because CloudFront
resources are global (not namespaced to a region), and the name must be
unique within an AWS account.
Note, for multiple deployments within an account we'd recommend using
a different ResourcePrefix, but we are fixing this as it worked in
previous releases. Added this to the deployment docs.
> Add the deployment region to OAC Name property

- .pre-commit-config.yaml
- CHANGELOG.md
- backend/ecs_tasks/delete_files/json_handler.py
- backend/ecs_tasks/delete_files/main.py
- backend/ecs_tasks/delete_files/requirements.in
- backend/ecs_tasks/delete_files/requirements.txt
- requirements.txt
- templates/template.yaml
- tests/acceptance/__init__.py
- tests/acceptance/test_job_cognito.py
- tests/acceptance/test_job_iam.py
- tests/unit/ecs_tasks/test_json.py
- tests/unit/ecs_tasks/test_main.py
Fix for a bug affecting gz json introduced in #358. It affected JSON gzipped objects, and the issue is that they are being written uncompressed. 
There are a couple of additional improvements included in this PR:
1. optimisations on Pre-commit hooks to run faster
2. Upgrade Apache Arrow from v8 to v13.
> Fix for a bug affecting gzip json being writtern in uncompressed format

- CHANGELOG.md
- backend/lambdas/data_mappers/handlers.py
- templates/template.yaml
- tests/unit/data_mappers/test_data_mappers.py
When Glue Tables are created manually, SerdeInfo/Parameters metadata can be omitted, breaking the validation logic in the Create Data Mapper API. This change fixes that by checking for Parameters metadata existence first.
> Parametersless metadata bugfix

- CHANGELOG.md
- backend/ecs_tasks/delete_files/json_handler.py
- templates/template.yaml
Increase the speed of the json_handler by migrating from a list to a set. Move from O(n) to O(1)
> Change list of match ids to set for json_handler.py

- CHANGELOG.md
- templates/auth.yaml
Some scanners are triggered by the presence of the `AmazonAPIGatewayInvokeFullAccessmanaged` policy. This commit replaces the managed policy with an equivalent inline policy that will not trigger scanners. There's a small security win in being able to scope the API Gateway resource to the specific Account and Region.
> Replace Managed Policy with equivalent inline policy

- .github/workflows/publish.yaml
- .github/workflows/unit-tests.yaml
- CHANGELOG.md
- docs/LOCAL_DEVELOPMENT.md
- package-lock.json
> Move to node18 and patch dependencies

- CHANGELOG.md
- templates/deletion_flow.yaml
- templates/template.yaml
Image scanning helps in identifying software vulnerabilities in your container images. Each repository can be configured to scan on push. This ensures that each new image pushed to the repository is scanned. You can then retrieve the results of the image scan. You can learn more [here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning.html). When Scan on Push is not enabled, images are not automatically scanned when they are pushed on to the repository. Vulnerabilities in your ECR images can affect the security posture of your containers or any applications running within them. Some scanners are triggered because the ECR repository doesn't enable ScanOnPush. 
Enable scan on push for the ECR repository used by the …
> Enable Scan On Push for the ECR Repository

- CHANGELOG.md
- backend/ecs_tasks/delete_files/json_handler.py
- backend/ecs_tasks/delete_files/main.py
- backend/ecs_tasks/delete_files/parquet_handler.py
- templates/template.yaml
- tests/unit/ecs_tasks/test_json.py
- tests/unit/ecs_tasks/test_main.py
- tests/unit/ecs_tasks/test_parquet.py
Follow-up PR from #395 - move the optimisation logic outside of the JSON handler to simplify logic and use less memory (as the hashmap is created at the start of the job, rather than copied on each line iterator).
I also included File Size in the log as it could be useful during troubleshooting.
> Improve JSON processing performance

- CHANGELOG.md
- cfn-publish.config
- templates/template.yaml
- templates/vpc.yaml
This PR reverts the enablement of the `eu-south-2` region due to failure in the deployment. Removing the region until we come up with a fix for the deployment.
> Reverted the eu-south-1 region enablement
