awslabs/amazon-s3-find-and-forget

- docs/LIMITS.md
We currently don't support glacier - including that in the limits.
> Clarify glacier limit

- .github/workflows/unit-tests.yaml
- Makefile
- README.md
- docs/LIMITS.md
- requirements.in
- requirements.txt
> Include codecov report after unit-tests

- CHANGELOG.md
- backend/lambdas/tasks/generate_queries.py
- docs/LIMITS.md
- frontend/src/__tests__/glueSerializer.js
- frontend/src/components/pages/NewDataMapper.js
- frontend/src/utils/glueSerializer.js
- tests/unit/tasks/test_generate_queries.py
We only support a number of data types. With this change, I updated the docs, plus I updated the frontend to make it easier to show what's allowed or not.
Note: Future PRs are coming for supporting more types.
I left out here particularly dates, decimal, and complex structures. One about struct in particular, will allow all the allowed types when nested inside structs. When that will happen, I'll update the docs too.
> More supported data types, docs update

- .github/PULL_REQUEST_TEMPLATE.md
This was driving me insane in every new PR.
> Fix typo in PR template.

- CHANGELOG.md
- frontend/package-lock.json
- package-lock.json
- templates/template.yaml
- Includes GitHub-generated dependency updates
- Bump version number to trigger a release
- CHANGELOG updated
> Release v0.6

- CHANGELOG.md
- docs/LIMITS.md
- templates/template.yaml
> Deploy new version

- CHANGELOG.md
- docs/LOCAL_DEVELOPMENT.md
- docs/USER_GUIDE.md
n/a
Update VPC info dead links in docs
> Fix Dead Links in Docs

- CHANGELOG.md
- frontend/package-lock.json
- frontend/package.json
- templates/template.yaml
> Upgrade react-scripts

- CHANGELOG.md
- frontend/src/components/pages/NewDataMapper.js
> UI Updates

- docs/COST_OVERVIEW.md
Some clarification about VPC cost. I thought about doing an estimate for a monthly cost, but to be honest the vpc pricing page already has a calculator that allows to have a quite decent idea for specific regions, so I just tried to put a note at the beginning + some clarification in each chapter.
Thoughts?
> More info about vpc costs

- CHANGELOG.md
- docs/UPGRADE_GUIDE.md
- templates/template.yaml
> Release v0.9

- CHANGELOG.md
- backend/ecs_tasks/delete_files/main.py
> Remove debugging line

- CHANGELOG.md
- backend/ecs_tasks/delete_files/s3.py
- tests/unit/ecs_tasks/test_s3.py
> Remove requester pays args for get object tagging

- CHANGELOG.md
- frontend/package-lock.json
> Upgrade dependencies

- CHANGELOG.md
- backend/lambdas/jobs/stream_processor.py
> Improve performance during cleanup phase

- CHANGELOG.md
- templates/template.yaml
> Release changes

- CHANGELOG.md
- frontend/package-lock.json
- frontend/package.json
- templates/template.yaml
> Dependencies update

- CHANGELOG.md
- docs/ARCHITECTURE.md
- docs/COST_OVERVIEW.md
- docs/LIMITS.md
Providing extra details regarding Athena costs and S3's eventual consistency model.
> Docs improvements

- README.md
- docs/PRODUCTION_READINESS_GUIDELINES.md
Some clarification on deploying to production.
> Intro docs

- CHANGELOG.md
- docs/USER_GUIDE.md
- templates/api.yaml
- templates/auth.yaml
- templates/state_machine.yaml
- templates/template.yaml
A fix and documentation for allowing using the solution with data registered with AWS Lake Formation.
> Lake Formation Integration

- .github/workflows/publish.yaml
- .github/workflows/release.yaml
Fix build: https://github.com/awslabs/amazon-s3-find-and-forget/actions/runs/380985786
Remove usage of deprecated `::set-env` command with github actions
> Remove usage of set-env

- CHANGELOG.md
- backend/lambdas/data_mappers/handlers.py
- backend/lambdas/data_mappers/schemas/get_data_mapper.json
- docs/api/Apis/DataMapperApi.md
- docs/api/README.md
- package-lock.json
- templates/api.definition.yml
- templates/api.yaml
- tests/acceptance/test_data_mappers.py
- tests/unit/data_mappers/test_data_mappers.py
Adds an endpoint to fetch information about a particular data mapper.
> GET datamapper endpoint

- CHANGELOG.md
- docs/USER_GUIDE.md
- templates/ddb.yaml
- templates/template.yaml
This is to make it easier for customers to create applications that integrate with the API, and need to create a stream to verify queue item creation/deletion.
> Export API Gateway URL + Deletion Queue Stream ARN

- .github/workflows/publish.yaml
- docs/USER_GUIDE.md
> Move to new GH pipeline

- CHANGELOG.md
- templates/template.yaml
> Release v0.25

- CHANGELOG.md
- frontend/package-lock.json
- package-lock.json
- requirements.in
- requirements.txt
> Upgrade Frontend and Build dependencies

- CHANGELOG.md
- docs/LIMITS.md
- templates/state_machine.yaml
- templates/template.yaml
> Fix cross-account bug

- docs/LIMITS.md
- docs/USER_GUIDE.md
This updates the deployment guide. There is an issue preventing people to deploy using Changeset #224 - this is to reflect that while we wait for a fix (I think that depends on a SAM bug)
> Fix deployment guide

- CHANGELOG.md
- templates/template.yaml
> Release v0.30

- CHANGELOG.md
- frontend/package-lock.json
- frontend/package.json
> Upgrade some frontend dependencies

- CHANGELOG.md
- templates/manifests.yaml
- templates/template.yaml
- templates/web_ui.yaml
> Restrict buckets actions too

- CHANGELOG.md
- frontend/package-lock.json
- frontend/package.json
> Upgrade frontend dependencies

- CHANGELOG.md
- templates/template.yaml
> Release new version

- CHANGELOG.md
- frontend/package-lock.json
- package-lock.json
- package.json
> Update JavaScript dependencies

- CHANGELOG.md
- templates/template.yaml
> Release v0.37

- CHANGELOG.md
- backend/lambdas/tasks/generate_queries.py
- tests/unit/tasks/test_generate_queries.py
Closes: #297 
Extends #297 to add a test and small fix, as well as updating the changelog.
> Add table name to error msg when col is not found

- CHANGELOG.md
- frontend/package-lock.json
> Upgrade frontend/simple-plist

- CHANGELOG.md
- templates/template.yaml
> Release new changes

- CHANGELOG.md
- templates/template.yaml
> Release v0.46

- CHANGELOG.md
- docs/SECURITY.md
*Description of changes:* Added a note to the documentation linking to how to enable MFA on Cognito.
- [n/a] Changelog updated
- [n/a ] Unit tests (and integration tests if applicable) provided
- [n/a] All tests pass
- [n/a] Pre-commit checks pass
- [n/a] Debugging code removed
- [n/a] If releasing a new version, have you bumped the version in the main CFN template?
> adde MFA note to documentation

- CHANGELOG.md
- package-lock.json
Closes #328 
Upgrade dependency without messing overrides.
> Update terser dependency

- Makefile
- docs/LOCAL_DEVELOPMENT.md
*Issue #, if available:* n/a
Adding missing dependancies to Local Development guide. There are no new dependancies it is just that these changes reflect what was always required but not listed before.
- [n/a] Changelog updated
- [n/a] Unit tests (and integration tests if applicable) provided
- [n/a] All tests pass
- [Y] Pre-commit checks pass
- [n/a] Debugging code removed
- [n/a] If releasing a new version, have you bumped the version in the main CFN template?
> dependancies list updated

- tests/acceptance/test_job_cognito.py
- tests/acceptance/test_job_iam.py
Closes #225 
There used to be an issue depending on S3FS failing to write 0-byte files with proper metadata, which we just fixed by removing the dependency from S3FS on #332 
This PR introduces a couple of acceptance tests to cover those use-cases.
> Add acceptance to test empty use-cases

- CHANGELOG.md
- requirements.in
- requirements.txt
> Upgrade build dependencies

- CHANGELOG.md
- docs/TROUBLESHOOTING.md
- docs/USER_GUIDE.md
- templates/api.yaml
- templates/state_machine.yaml
- templates/stream_processor.yaml
- templates/template.yaml
Adds flexibility when configuring resources and removes the need of manually changing things creating snowflakes.
> Allow configuring Lambda Memory

- CHANGELOG.md
- templates/template.yaml
*Issue #, if available:* N/A
Release v0.59.
Intending to merge this once #362 and #363 are merged.
> Release v0.59

- CHANGELOG.md
- package-lock.json
> Update frontend dependencies
